const express = require("express");
console.log("🔥 THIS IS MY SERVER FILE");
const cors = require("cors");
const nodemailer = require("nodemailer");
require("dotenv").config();

const app = express();

app.use(cors());
app.use(express.json());

// Home Route
app.get("/", (req, res) => {
  res.send("Backend is Running 🚀");
});

// Send Email Route
app.post("/send-email", async (req, res) => {

    console.log("✅ POST /send-email reached");
    console.log(req.body);
  try {
    const {
      company,
      reporter,
      email,
      incidentType,
      severity,
      system,
      description,
    } = req.body;

    const transporter = nodemailer.createTransport({
      service: "gmail",
      auth: {
        user: process.env.EMAIL_USER,
        pass: process.env.EMAIL_PASS,
      },
    });

    await transporter.sendMail({
        
      from: process.env.EMAIL_USER,
      to: email,
      subject: `[${severity}] ${incidentType} Detected - ${system}`,
      html: `
        <h2>🚨 Security Incident Notification</h2>

        <p><strong>Company:</strong> ${company}</p>
        <p><strong>Reporter:</strong> ${reporter}</p>
        <p><strong>Email:</strong> ${email}</p>
        <p><strong>Incident:</strong> ${incidentType}</p>
        <p><strong>Severity:</strong> ${severity}</p>
        <p><strong>Affected System:</strong> ${system}</p>

        <h3>Description</h3>

        <p>${description}</p>

        <hr>

        <p><strong>Generated by SecureOps AI</strong></p>
      `,
    });
console.log("✅ Email Sent Successfully");
    res.json({
      success: true,
      message: "Email Sent Successfully",
    });

  } catch (err) {
    console.error(err);

    res.status(500).json({
      success: false,
      message: err.message,
    });
  }
});

const PORT = 5000;
app._router.stack.forEach((r) => {
  if (r.route) {
    console.log(
      Object.keys(r.route.methods).join(",").toUpperCase(),
      r.route.path
    );
  }
});
app.listen(PORT, () => {
  console.log(`Server is running on port ${PORT}`);
});