import {
  FaFileAlt,
  FaShieldAlt,
  FaEnvelope,
  FaDownload,
} from "react-icons/fa";

import jsPDF from "jspdf";
import emailjs from "@emailjs/browser";
function IncidentReport({ reportData }) {

  // ================= DOWNLOAD PDF =================

  const downloadPDF = () => {
    const pdf = new jsPDF();

    pdf.setFontSize(22);
    pdf.text("SecureOps AI Incident Report", 20, 20);

    pdf.setFontSize(14);

    pdf.text(`Company: ${reportData?.company || "N/A"}`, 20, 40);
    pdf.text(`Reporter: ${reportData?.reporter || "N/A"}`, 20, 50);
    pdf.text(`Email: ${reportData?.email || "N/A"}`, 20, 60);

    pdf.text(`Incident: ${reportData?.incidentType || "N/A"}`, 20, 80);
    pdf.text(`Severity: ${reportData?.severity || "N/A"}`, 20, 90);
    pdf.text(`Affected System: ${reportData?.system || "N/A"}`, 20, 100);

    pdf.text("Description:", 20, 120);

    const lines = pdf.splitTextToSize(
      reportData?.description || "No Description",
      170
    );

    pdf.text(lines, 20, 130);

    pdf.text("Status: Under Investigation", 20, 200);

    pdf.text(
      `Generated: ${new Date().toLocaleString()}`,
      20,
      215
    );

    pdf.save("SecureOps-Incident-Report.pdf");
  };


  // ================= SEND EMAIL =================

  const sendEmail = async () => {
    try {

      const templateParams = {
        company: reportData?.company,
        reporter: reportData?.reporter,
        email: reportData?.email,
        incidentType: reportData?.incidentType,
        severity: reportData?.severity,
        system: reportData?.system,
        description: reportData?.description,
        
      };
      
      console.log(templateParams);
console.log("Template Params:", templateParams);
      await emailjs.send(
        "service_hk77361",
        "template_fswmrwo",
        templateParams,
        "YGVBX1L9aILCU6sCd"
      );

      alert("✅ Email Sent Successfully!");

    } catch (error) {

      console.error(error);
      alert("❌ Email Failed");

    }
  };


  return (

    <div className="incident-report glass-card">

      <div className="report-header">

        <h2>
          <FaFileAlt />
          Incident Report
        </h2>

        <div className="report-actions">

          <button className="copy-btn" onClick={sendEmail}>
            <FaEnvelope />
            Send Email
          </button>

          <button
            className="download-btn"
            onClick={downloadPDF}
          >
            <FaDownload />
            Download PDF
          </button>

        </div>

      </div>

      <div className="report-content">
        {/* ================= EXECUTIVE SUMMARY ================= */}

<section className="report-section">

  <h3>
    <FaShieldAlt />
    Executive Summary
  </h3>

  <p>
    A cybersecurity incident has been identified and analyzed by
    SecureOps AI. Initial investigation indicates that the affected
    systems require immediate containment to minimize operational
    disruption and reduce potential business impact.
  </p>

</section>

{/* ================= INCIDENT DETAILS ================= */}

<section className="report-section">

  <h3>Incident Details</h3>

  <table className="report-table">

    <tbody>

      <tr>
        <td><strong>Company</strong></td>
        <td>{reportData?.company || "Not Available"}</td>
      </tr>

      <tr>
        <td><strong>Reporter</strong></td>
        <td>{reportData?.reporter || "Not Available"}</td>
      </tr>

      <tr>
        <td><strong>Email</strong></td>
        <td>{reportData?.email || "Not Available"}</td>
      </tr>

      <tr>
        <td><strong>Incident Type</strong></td>
        <td>{reportData?.incidentType || "Not Available"}</td>
      </tr>

      <tr>
        <td><strong>Severity</strong></td>
        <td>{reportData?.severity || "Not Available"}</td>
      </tr>

      <tr>
        <td><strong>Affected System</strong></td>
        <td>{reportData?.system || "Not Available"}</td>
      </tr>

      <tr>
        <td><strong>Description</strong></td>
        <td>{reportData?.description || "Not Available"}</td>
      </tr>

      <tr>
        <td><strong>Status</strong></td>
        <td>Under Investigation</td>
      </tr>

      <tr>
        <td><strong>Generated By</strong></td>
        <td>SecureOps AI</td>
      </tr>

    </tbody>

  </table>

</section>
{/* ================= INCIDENT TIMELINE ================= */}

<section className="report-section">

  <h3>Incident Timeline</h3>

  <ul className="timeline">

    <li>
      <strong>08:15 AM</strong> - Suspicious activity detected by monitoring system.
    </li>

    <li>
      <strong>08:22 AM</strong> - Security team received automated alert.
    </li>

    <li>
      <strong>08:40 AM</strong> - Affected systems isolated from the network.
    </li>

    <li>
      <strong>09:10 AM</strong> - Incident response process initiated.
    </li>

    <li>
      <strong>09:45 AM</strong> - Initial investigation completed.
    </li>

  </ul>

</section>

{/* ================= CONTAINMENT ACTIONS ================= */}

<section className="report-section">

  <h3>Containment Actions</h3>

  <ul>

    <li>✔ Isolated affected systems from the network.</li>

    <li>✔ Blocked malicious IP addresses and domains.</li>

    <li>✔ Disabled compromised user accounts.</li>

    <li>✔ Preserved forensic evidence for investigation.</li>

    <li>✔ Notified the Security Operations Center (SOC).</li>

  </ul>

</section>

{/* ================= RECOVERY ACTIONS ================= */}

<section className="report-section">

  <h3>Recovery Actions</h3>

  <ul>

    <li>Restore affected systems from verified backups.</li>

    <li>Apply latest security patches and updates.</li>

    <li>Reset credentials for impacted users.</li>

    <li>Perform malware scan across all critical assets.</li>

    <li>Continue monitoring for any signs of reinfection.</li>

  </ul>

</section>

{/* ================= SECURITY RECOMMENDATIONS ================= */}

<section className="report-section">

  <h3>Security Recommendations</h3>

  <ul>

    <li>Enable Multi-Factor Authentication (MFA) for all users.</li>

    <li>Conduct organization-wide phishing awareness training.</li>

    <li>Implement Endpoint Detection & Response (EDR) across all endpoints.</li>

    <li>Review firewall rules and network segmentation policies.</li>

    <li>Schedule regular vulnerability assessments and penetration testing.</li>

    <li>Maintain offline and immutable backups for critical business data.</li>

  </ul>

</section>
{/* ================= AI GENERATED EMAIL ================= */}

<section className="report-section">

  <h3>
    <FaEnvelope />
    AI Generated Incident Email
  </h3>

  <div className="email-preview">

    <p><strong>Subject:</strong> Critical Security Incident Notification</p>

    <br />

    <p>Dear Team,</p>

    <br />

    <p>
      A <strong>{reportData?.severity || "security"}</strong> severity{" "}
      <strong>{reportData?.incidentType || "incident"}</strong> has been
      reported affecting{" "}
      <strong>{reportData?.system || "the organization"}</strong>.
    </p>

    <p>
      <strong>Company:</strong> {reportData?.company || "N/A"}
    </p>

    <p>
      <strong>Reported By:</strong> {reportData?.reporter || "N/A"}
    </p>

    <p>
      <strong>Description:</strong>{" "}
      {reportData?.description || "No Description"}
    </p>

    <br />

    <p>
      SecureOps AI recommends immediate containment, investigation,
      and recovery actions.
    </p>

    <br />

    <p>
      Regards,
      <br />
      <strong>SecureOps AI</strong>
      <br />
      Security Operations Center
    </p>

  </div>

</section>

</div>

{/* ================= FOOTER ================= */}

<div className="report-footer">

  <p>
    <strong>Report Generated By:</strong> SecureOps AI
  </p>

  <p>
    <strong>Classification:</strong> Confidential
  </p>

  <p>
    <strong>Status:</strong> Ready for Distribution
  </p>

  <p>
    <strong>Generated On:</strong> {new Date().toLocaleString()}
  </p>

</div>

</div>

);
}

export default IncidentReport;